sudo: required
language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-9
            - g++-9

before_install:
  - wget https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4.tar.gz
  - tar -xf cmake-3.15.4.tar.gz
  - sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.15.4/bin/cmake /home/travis/bin/cmake
  - sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.15.4/bin/ctest /home/travis/bin/ctest

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - ctest .
