dist: bionic
sudo: required
language: cpp

compiler:
  - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-9
            - g++-9

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - ctest .
