os: linux
language: cpp
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8

before_install:
  - which gcc
  - sudo rm -rf /usr/local/cmake-3.12.4

# the install step will take care of deploying a newer cmake version
install:    
  # first we create a directory for the CMake binaries
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  # we use wget to fetch the cmake binaries
  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5-Linux-x86_64.tar.gz
  # extract the binaries; the output here is quite lengthy,
  # so we swallow it to not clutter up the travis console
  - tar -xvf cmake-3.15.5-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.15.5-Linux-x86_64 cmake-install
  # add both the top-level directory and the bin directory from the archive
  # to the system PATH. By adding it to the front of the path we hide the
  # preinstalled CMake with our own.
  - export PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  # don't forget to switch back to the main build directory once you are done
  - cd ${TRAVIS_BUILD_DIR}
  
  # Install ninja
  - sudo apt-get install ninja-build
  
  # Install SDL2
  - sudo apt-get install libsdl2-dev

before_script:
  - sudo ln -s /usr/bin/gcc-5.4 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-5.4 /usr/local/bin/g++
  
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-5.4
  - export CXX=/usr/bin/g++-5.4
  
  - gcc -v && g++ -v && cmake --version

script:
  - mkdir build && cd build
  - cmake -G Ninja ..
  - cmake --build .
  - ctest .
