sudo: required
language: cpp

compiler:
  - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-9
            - g++-9


install:    
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4.tar.gz

  - tar -xvf cmake-3.15.4.tar.gz > /dev/null
  - mv cmake-3.15.4 cmake-install
 
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cmake .
  - cmake --build .
  - ctest .
