version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release
  - Debug

install:
    - git submodule update --init --recursive
    - %MSVC% vcpkg install sdl2:%PLATFORM%-windows sdl2-image:%PLATFORM%-windows sdl2-mixer:%PLATFORM%-windows expat:%PLATFORM%-windows glew:%PLATFORM%-windows gettext:%PLATFORM%-windows
before_build:
    - cmake -G "Visual Studio 15 2017 Win64" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\unit-tests.exe'
