version: '1.0.{build}'

image: Visual Studio 2019

init:
  - vcpkg install sdl2:x64-windows
  - vcpkg integrate install

platform:
  - x64
 
configuration:
  - Release

install:
  - git submodule update --init --recursive
    
before_build:
  - cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 16 2019" -A x64 02-sdl

build:
  project: $(APPVEYOR_BUILD_FOLDER)\sdl-hello-world.sln
  
test_script:
  - '%APPVEYOR_BUILD_FOLDER%\sdl-static\%CONFIGURATION%\sdl-main-static.exe'
  - '%APPVEYOR_BUILD_FOLDER%\sdl-shared\%CONFIGURATION%\sdl-main-shared.exe'
  
cache: c:\tools\vcpkg\installed\
